spring:
  application:
    name: Chaos Theory
  profiles:
   active: development

server:
  port: 9090

servlet:
  container:
    maxThreads: 15

---

spring:
  profiles: development
  profiles.include: h2

---
spring:
  profiles: production
  profiles.include: db

---

spring:
  profiles: test
  profiles.include: h2

---

spring:
  profiles: db
  datasource:
    url: jdbc:mysql://localhost:3306/koko
    username: megaUser
    password:
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect

---

spring:
  profiles: h2
  datasource:
    url: jdbc:h2:mem:AZ
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
